run:
    go: 1.22
linters:
    enable:
        - thelper
        - gofumpt
        - tparallel
        - unconvert
        - unparam
        - wastedassign
        - revive
        - forbidigo
        - tagliatelle
        - misspell
