name: Lint

on:
    workflow_dispatch:
    pull_request:
        branches: [ main ]

jobs:
    lint:
        name: Lint Go
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [ 1.22.x ]
        steps:
            # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            # Step 2 - Install Go on the runner
            -   name: Install Go
                uses: actions/setup-go@v3
                with:
                    go-version: ${{ matrix.go-version }}

            # Step 3 - Lint
            -   name: Lint
                uses: golangci/golangci-lint-action@v6
                with:
                    version: latest
                    skip-go-installation: true
                    skip-pkg-cache: true
                    args: --verbose
                    timeout: 5m

            # Step 3 - Run git diff
            -   name: Diff
                run: git diff
